"use client"
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.scss";
import { Provider } from "react-redux";
import store from "./Store/store";
import Footer from "./components/footer/footer";
import Topbar from "./components/topbar/topbar";
const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const isClient = typeof window !== 'undefined';

  return (
  //   <html lang="en" suppressHydrationWarning>
  //     <body className={inter.className}>
  //   <div className="App">
  //   {isClient && (
  //   <Provider store={store}>
      
  //     {/* <Topbar></Topbar> */}
  //     {/* <MainBar></MainBar> */}
      
  //       {children}
  //     <Footer></Footer>
  //     {/* <LiveChat></LiveChat> */}
  //   </Provider>
  //   )}
  // </div>
  // </body>
  // </html>
    <html lang="en">
      <body className={inter.className}>
        </body>
    </html>
  );
}
